### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by vmodha** [BananoCoin/kalium_wallet_flutter#13]
When running `flutter build ios` I'm getting the following error:

[!] Unable to determine Swift version for the following pods:

- `vibrate` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

[!] Automatically assigning platform `ios` with version `10.3` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by bbedward** [comment]
Current master works with cocoapods 1.8+ and flutter 1.17
