### ISSUE TITLE
I am trying to run this for the first time and I keep getting this error.

### ISSUE THREAD

**Issue by shakilahmed731** [BananoCoin/kalium_wallet_flutter#15]
Because every version of local_auth from git depends on intl ^0.15.1 and kalium_wallet_flutter depends on intl ^0.16.0, local_auth from git is forbidden.

**Comment by atlaschiew** [comment]
yes i am facing this error as well. kindly advise

**Comment by bbedward** [comment]
Did you alter the dependencies?

Kalium pubspec specifies intl intl: ^0.15.8

**Comment by atlaschiew** [comment]
hi, bbedward, no help from your suggestion. in pubspec.yaml, i try to delete the line with intl: ^0.15.8 to check vary of message. now i got this.

```
Running "flutter pub get" in kalium_wallet_flutter-master...     
Because every version of local_auth from git depends on intl ^0.15.1 and every version of flutter_localizations from sdk depends on intl 0.16.1, local_auth from git is incompatible with flutter_localizations from sdk.

So, because kalium_wallet_flutter depends on both flutter_localizations any from sdk and local_auth from git, version solving failed.
pub get failed (1; So, because kalium_wallet_flutter depends on both flutter_localizations any from sdk and local_auth from git, version solving failed.)
```

**Comment by bbedward** [comment]
you probably need to use an older version of flutter, or update all the dependencies to newer versions

**Comment by atlaschiew** [comment]
@bbedward , hi, i have downgraded my flutter from v1.12.13 to v1.5.4, and error now displaying

`Because kalium_wallet_flutter depends on flutter_web_plugins any from sdk which doesn't exist (could not find package flutter_web_plugins in the Flutter SDK), version solving failed.`

can you suggest me which older flutter version should i install?

**Comment by atlaschiew** [comment]
> @bbedward , hi, i have downgraded my flutter from v1.12.13 to v1.5.4, and error now displaying
> 
> `Because kalium_wallet_flutter depends on flutter_web_plugins any from sdk which doesn't exist (could not find package flutter_web_plugins in the Flutter SDK), version solving failed.`
> 
> can you suggest me which older flutter version should i install?

okay, i add url_launcher: ^0.4.2 in dependencies block of pubspec.yaml, and this error just vanish, and only now new error suggest me version of sdk

`Because kalium_wallet_flutter depends on flutter_svg >=0.13.0 which requires Flutter SDK version >=1.5.9-pre.94 <2.0.0, version solving failed.`

**Comment by atlaschiew** [comment]
> > @bbedward , hi, i have downgraded my flutter from v1.12.13 to v1.5.4, and error now displaying
> > `Because kalium_wallet_flutter depends on flutter_web_plugins any from sdk which doesn't exist (could not find package flutter_web_plugins in the Flutter SDK), version solving failed.`
> > can you suggest me which older flutter version should i install?
> 
> okay, i add url_launcher: ^0.4.2 in dependencies block of pubspec.yaml, and error above just vanish, and only now new error suggest me version of sdk
> 
> `Because kalium_wallet_flutter depends on flutter_svg >=0.13.0 which requires Flutter SDK version >=1.5.9-pre.94 <2.0.0, version solving failed.`

hi guys, flutter sdk v1.9.1 manage to run kalium :)
