### ISSUE TITLE
QR code scanning with amount is broken

### ISSUE THREAD

**Issue by jdrowell** [BananoCoin/kalium_wallet_flutter#32]
This worked until the current release (v2.3.2). The logic below seems to be broken (should be <= ?)

https://github.com/BananoCoin/kalium_wallet_flutter/blob/d0e297c73fca715fa69ee3085cf30ce83fdb5d74/lib/ui/send/send_sheet.dart#L610

This is currently breaking JungleTV, as the amount to queue videos is not showing up (people can still type it in later).

Example QR that should scan to 22.68 BAN:

ban:ban_177bxqook7croj1rhysc96q915rh5hmt8hoap94wxxh449f9zwe97pgmmne9?amount=2268000000000000000000000000000

**Comment by bbedward** [comment]
I will fix it and get a release out today, as a temp workaround you can swipe up from the send button to scan QR codes that way.

**Comment by jdrowell** [comment]
Thanks. BTW the scanning is working fine from the "Scan QR Code" button, the address is detected correctly, only the recent logic change after that, for validating the amount, seems to be breaking things. Kalium says things like "minimum value to send is 0.0001" even if amount is correct (and higher than the minimum).

**Comment by bbedward** [comment]
Yes I know, I mean from the home page you can swipe up from the send button and access the QR scanner that way - the amount logic is working there still. As a workaround until the update rolls out

**Comment by bbedward** [comment]
Fixed in 554428d238a5bad3b55a55f8169f448bcbfdfe45

**Comment by jdrowell** [comment]
> from the home page

Ah I see, I didn't know that, cool feature. So it's a different code path.
