### ISSUE TITLE
v2.3.4 breaking bug when importing from seed

### ISSUE THREAD

**Issue by thekesslereffect** [BananoCoin/kalium_wallet_flutter#36]
Hey guys, 

Updated to v2.3.4 and everything was working fine. I then proceeded to delete my seed and create a new wallet. Now the wallet wont display transactions and I don't have the ability to send. It does however send me notifications whenever I am sent Banano. 
![IMG_6347](https://user-images.githubusercontent.com/24286691/143836489-3b0c96fb-36e4-40b4-ad8f-6b1ee909fe42.png)

**Comment by thekesslereffect** [comment]
This has been confirmed by several people in the frankenstein channel in discord.

**Comment by zcyph** [comment]
I am experiencing this issue as well, except it's not only when importing from seed. As soon as I upgraded to 2.3.4, Kalium loads the monkey avatar, but the rest of the values like balance, value, and transaction history never load. This is on a OnePlus 3T running DivestOS (a fork of LineageOS) with an essentially blank hosts file and nothing occupying the VPN slot. Kalium always worked perfectly up til this update. Clearing cache, data, uninstalling and reinstalling, connecting from data vs WiFi, connecting on a VPN vs not on a VPN, none of that made any difference.

**Comment by bbedward** [comment]
This was fixed with a server side change
