### ISSUE TITLE
Change Representative List DataSource

### ISSUE THREAD

**Issue by dev-ptera** [BananoCoin/kalium_wallet_flutter#42]
### What's Happening Now

Kalium currently pulls the list of representatives directly from YellowSpyglass's backend, specifically from these two sources:

**Representatives**
https://api.yellowspyglass.com/yellowspyglass/representatives

**Aliases**
https://api.yellowspyglass.com/yellowspyglass/aliases

Scores are then calculated within Kalium.

### What I'd like to See Happen 

I would like to see Kalium update its datasource to use Spyglass API's representative score API so that scores can be consistent between YellowSpyglass, Kalium, and the hardware wallet I'm working on.

**API**
https://api.spyglass.pw/banano/v1/representatives/scores

**Docs**
https://spyglass-api.web.app/representatives/scores

If this is something that the maintainers are okay with changing, I'd like to attempt to implement the change since I've never worked with flutter before & it'd be good experience.   Please let me know your thoughts.

**Comment by yekta** [comment]
Thanks for the suggestion but we are happy with our way of scoring. We might also change the scoring system again at some point. I don’t see a need for the scores to be consistent between the apps.
