### ISSUE TITLE
Did biometrics break?

### ISSUE THREAD

**Issue by jdrowell** [BananoCoin/kalium_wallet_flutter#48]
Went to use Kalium just now to send BAN, it didn't ask me for fingerprint like it always does, went straight to PIN (which I had, but never used before). App says it's version 2.4.0, even though there is not 2.4.0 release (yet, committed to master but no release). Could it have broken because of https://github.com/BananoCoin/kalium_wallet_flutter/commit/cbffd18f05e970c1cbe6424d24706135d8a8031d?

This is on Android, old Moto G7play running Android 10, default firmware.

**Comment by bbedward** [comment]
It should be resolved on v2.4.1, I forgot to publish the github release but it's there now. Please see if it persists on the newer version.
