### ISSUE TITLE
can't get it to run due to return await compute(_downloadOrRetrieveMonkey, {'fileName': fileName, 'url':url});

### ISSUE THREAD

**Issue by jkibasui** [BananoCoin/kalium_wallet_flutter#6]
Initializing gradle...                                            112.6s
Resolving dependencies...                                           8.3s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                                                                        
Compiler message:                                                       
lib/ui/util/ui_util.dart:454:26: Error: The argument type 'Future<File> Function(Map<String, String>)' can't be assigned to the parameter type 'File Function(Map<String, String>)'.
 - 'Future' is from 'dart:async'.                                       
 - 'File' is from 'dart:io'.                                            
 - 'Map' is from 'dart:core'.                                           
Try changing the type of the parameter, or casting the argument to 'File Function(Map<String, String>)'.
    return await compute(_downloadOrRetrieveMonkey, {'fileName': fileName, 'url':url});
                         ^                                              
Compiler failed on /Users/joe/Development/Android/kalium_wallet_flutter-master/lib/main.dart
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        49.1s
Gradle task assembleDebug failed with exit code 1

**Comment by bbedward** [comment]
Yea the ability to use the computer function with a future is not available in flutter stable yet.

You can switch to the dev channel to get it to build again.

```
flutter channel dev
flutter upgrade
```
