### ISSUE TITLE
Upgraded to Flutter dev channel and got the following error

### ISSUE THREAD

**Issue by aravindmj97** [BananoCoin/kalium_wallet_flutter#7]
Compiler message:
file:///C:/flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.5.0/lib/flare.dart:1023:18: Error: The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^
Compiler failed on D:\Android_Projects\kalium_wallet_flutter\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by bbedward** [comment]
For now we only support building on stable flutter.

But flare itself has different branches on its github for stable, beta, dev, master. They should be compatible with the whichever channel you use.
